language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage
  - pip install git+https://github.com/ShineyDev/prettify.py.git
  - pip install discord.py==1.5.1
  - pip install sly

script:
  - coverage run test.py
  - coverage report -m
